# ---- EDIT THESE ----
title: Tyler Matteson
tagline: Graduate Student at Stanford
email: tylerjm@stanford.edu
# Social links (delete any you don't want)
github: tylermatteson22
linkedin: tyler-j-matteson

# ---- Leave the rest alone ----
markdown: kramdown
